language: node_js
sudo: required
dist: trusty
node_js:
  - '8'
  - '10'
  - '11'
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest coveralls codecov --quiet
install:
  - npm ci --quiet
before_script:
  - npm run ts
script:
  - npm t
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
