language: node_js
sudo: required
dist: trusty
node_js:
  - '8'
  - '10'
  - '11'
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest
install:
  - npm ci --quiet
before_script:
  - npm run ts
script:
  - npm run test:ci
