environment:
  CODECOV_TOKEN:
    secure: 5SygvlgfTewBB3CTmBxUfQ==
  SNYK_TOKEN:
    secure: IyV3vkSZTlBKOtJfcNFk3ZyRSwSRKZUg4YUulfphVR8FCMj94J7az6yIoqNALOPq
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
