install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm
  - npm install

platform:
  - x86
  - x64
  - ARM

test_script:
  - node --version
  - npm --version
  - npm test

build: off
